<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var \Application\Entity\Cliente $cliente // Supondo que você passou a entidade Cliente para a view
 */
?>

<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Editando <?= $this->escapeHtml($cliente->nome); ?></h1>
    <hr>
    <form action="/clientes/<?= $cliente->id ?>" method="post">
        <?= $this->partial('application/clientes/form-partial.phtml', ['cliente' => $cliente]); ?>
    </form>
</div>
