<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 * @var \Application\Entity\Cliente $cliente
 */
?>

<div class="mb-3">
    <label for="nome" class="form-label">Nome</label>
    <input type="text" class="form-control" id="nome" name="nome" value="<?= isset($cliente) ? $this->escapeHtml($cliente->nome) : ''; ?>">
</div>
<div class="mb-3">
    <label for="email" class="form-label">Email</label>
    <input type="email" class="form-control" id="email" name="email" value="<?= isset($cliente) ? $this->escapeHtml($cliente->email) : ''; ?>">
</div>
<div class="mb-3">
    <label for="telefone" class="form-label">Telefone</label>
    <input type="text" class="form-control" id="telefone" name="telefone" value="<?= isset($cliente) ? $this->escapeHtml($cliente->telefone) : ''; ?>">
</div>
<div class="mb-3">
    <label for="endereco" class="form-label">Endereço</label>
    <input type="text" class="form-control" id="endereco" name="endereco" value="<?= isset($cliente) ? $this->escapeHtml($cliente->endereco) : ''; ?>">
</div>
<button type="submit" class="btn btn-primary">Salvar</button>