<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="p-5 mb-4 bg-light rounded-3">
    <h1 class="display-4">Bem-vindo ao Desafio Laminas!</h1>
    <p class="lead">
        Este projeto é fruto da paixão pelo ensino e pela programação. Desenvolvido passo a passo com os alunos do <a href="https://www.torneseumprogramador.com.br/" target="_blank">Torne-se um Programador</a>, buscamos aqui demonstrar o poder e a flexibilidade do framework Laminas.
    </p>
    <p>
        Se você está vendo esta página, está no início de uma incrível jornada de aprendizado. A cada linha de código, a cada desafio superado, você não apenas se torna um programador melhor, mas contribui para uma comunidade de aprendizes e profissionais dedicados.
    </p>
    <a href="https://www.torneseumprogramador.com.br/cursos/desafio_php" target="_blank" class="btn btn-primary btn-lg">Saiba mais sobre o desafio</a>
</div>
